// AUTO-GENERATED by Bat2C program
// that was written by blek
// 
// compile like this(minimum size, but may be hard):
// cl out.c
// crinkler [object.obj] user32.lib kernel32.lib
// 
// or this(bigger size(still pretty small tho), but WAY easier):
// tcc out.c 

#include <stdlib.h>

int main() {
    // Simple program
    system("@ECHO OFF");
    system("ECHO hi!");
    system("PAUSE");
}

